apiVersion: v1
kind: Secret            # "Secret"
metadata:
  name: mongo-secret    # an arbitrary name
type: Opaque            # "Opaque" - default for arbitrary key-value pairs
data:                   # the actual contents -> key-value pairs
  mongo-user: abc       # should encode by base64 -> echo -n <value> | base64
  mongo-password: abc