apiVersion: v1
kind: ConfigMap         # "ConfigMap"
metadata: 
  name: mongo-config    # an arbitrary name
data:                   # they actual contents -> key-value pair
  mongo-url: mongo-service


# Step 1: kubectl apply -f mongo-config.yaml
# Step 2: kubectl apply -f mongo-secret.yaml
# Step 3: kubectl apply -f mongo.yaml
# Step 4: kubectl apply -f webapp.yaml

# kubectl get all -> get all components
# kubectl get [node, pod, configmap, secret,...]
# kubectl describe <category - deployment, service,...> <instance>
# kubectl logs <pod name>
